
-- +migrate Up
CREATE TABLE items (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name   varchar(255) NOT NULL,
    url    text NOT NULL
);

-- +migrate Down
DROP TABLE IF EXISTS items;
