language: go

go:
  - master

before_install:
    - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
      && curl -LO 'https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip'
      && unzip protoc-3.6.1-linux-x86_64.zip
      && popd
    - export PATH=$HOME/protobuf/bin:$PATH
    - go get -u github.com/golang/dep/cmd/dep
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - make generate_go
    - cd server/

install:
    - make vendor

script:
    - make unit_test
