FROM golang:alpine

ARG UID
ARG GID

RUN apk add --update \
    git \
    bash \
    nodejs \
    yarn \
    make \
    g++ \
    postgresql-client && \
    go get -v github.com/rubenv/sql-migrate/... && \
    go get -u github.com/golang/dep/cmd/dep && \
    adduser -D -u ${UID} readstack-developer && \
    chown -R readstack-developer /go

USER $UID:$GID
