version: '3.4'

networks:
  dev:
    driver: bridge

volumes:
    db:

services:
  app:
    image: golang:alpine
    volumes:
      - ${PWD}:/go/src/github.com/jlevesy/readstack
    networks:
      - dev
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=readstack
      - POSTGRES_PASSWORD=notsecret
      - POSTGRES_DB=readstack
    volumes:
        - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dev
