version: '3.4'

networks:
  dev:
    driver: bridge

volumes:
    db:

services:
  front:
    image: node:alpine
    volumes:
      - ${PWD}/web:/home/node/app
    working_dir: /home/node/app
    environment:
      - READSTACK_BACKEND_URL=http://app:8080
    ports:
      - 8081:8081
    command:
      - yarn
      - container-start
    depends_on:
      - app
    networks:
      - dev

  app:
    image: golang:alpine
    working_dir: /go/src/github.com/jlevesy/readstack
    volumes:
      - ${PWD}:/go/src/github.com/jlevesy/readstack
    networks:
      - dev
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
        - READSTACK_POSTGRES_URL=postgres://readstack:notsecret@db:5432/readstack?sslmode=disable
        - READSTACK_LISTEN_PORT=8080
        - READSTACK_HANDLER_TIMEOUT=200ms
        - READSTACK_WEB_ASSETS_PATH=dist/web
    command:
      - go
      - run
      - cmd/server/main.go
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=readstack
      - POSTGRES_PASSWORD=notsecret
      - POSTGRES_DB=readstack
    volumes:
        - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dev
