version: '3.4'

networks:
  dev:
    driver: bridge

volumes:
    db:

services:
  app:
    image: golang:alpine
    working_dir: /go/src/github.com/jlevesy/readstack
    volumes:
      - ${PWD}:/go/src/github.com/jlevesy/readstack
    networks:
      - dev
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
        - READSTACK_POSTGRES_URL=postgres://readstack:notsecret@db:5432/readstack?sslmode=disable
        - READSTACK_LISTEN_PORT=8080
        - READSTACK_HANDLER_TIMEOUT=200ms
        - READSTACK_WEB_ASSETS_PATH=dist/web
    command:
      - go
      - run
      - server/cmd/api/main.go
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=readstack
      - POSTGRES_PASSWORD=notsecret
      - POSTGRES_DB=readstack
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - dev
