#! /bin/sh
docker network create readstack_dev

docker run
    -ti \
     --rm \
    -w /go/src/github.com/jlevesy/readstack \
    -v ${PWD}:/go/src/github.com/jlevesy/readstack \
    --network readstack_dev \
    readstack-toolbox \
    $@
